# Generated by Django 5.1.6 on 2025-02-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_taskdetail_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='asset',
            field=models.ImageField(blank=True, default='tasks_assets/default_img.jpg', null=True, upload_to='tasks_asset'),
        ),
    ]
